### ISSUE TITLE
OOM while trying to allocate a (seg_len, num_segments, nlags*latent_dim, nlags*latent_dim) array

### ISSUE THREAD

**Issue by r-shruthi11** [dattalab/jax-moseq#25]
As the title describes, `resample_continuous_stateseq` tried to allocate an array of size `(seg_len, segments, nlags, latent_dim)` and runs out of memory. 

```
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 125848448880 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  884.63MiB
              constant allocation:       796B
        maybe_live_out allocation:  404.04MiB
     preallocated temp allocation:  117.21GiB
                 total allocation:  118.46GiB
Peak buffers:
	Buffer 1:
		Size: 56.80GiB
		Operator: op_name="jit(resample_continuous_stateseqs)/jit(main)/jit(resample_continuous_stateseqs)/broadcast_in_dim[shape=(10027, 330, 48, 48) broadcast_dimensions=()]"
		XLA Label: broadcast
		Shape: f64[10027,330,48,48]
		==========================

```

This is after I set `XLA_PYTHON_CLIENT_PREALLOCATE=false` 
I haven't been able to isolate exactly where this is coming from within `resample_continuous_stateseq` but could `ar_to_lds` be a candidate? If yes, then this is potentially a bug because  the argument `A` is supposed to have shape `(states, latent_dim, ar_dim)`

**Comment by calebweinreb** [comment]
We can look into this, but generally the shapes that cause OOM errors can be counterintuitive since they arise as intermediates deep inside functions that are being vmap'd etc. 

Is this error happening for a dataset that you were able to process previously? Or is it bigger?

**Comment by r-shruthi11** [comment]
You're right - this is coming from `jax.vmap` trying to broadcast `A_, b_, ...., ` upto to the same batch dims as `z, y` in the call to `kalman_sample` within `resample_continuous_stateseq` 

This is an error with a larger dataset (so likely not a new error) - but I've been trying to workout whether this is the most memory efficient call to `jax.vmap`

**Comment by calebweinreb** [comment]
It's a good question whether we could do this more efficiently... 

Just to recap:
- You have a dataset with 330 sequences of length 10027 (after being chunked by keypoint_moseq)
- In order to do Kalman sampling with non-stationary dynamics/noise, it's necessary to pass dynamics and noise matrices for each frame. These matrices have shape (48,48) on each frame, so in total you get arrays of size [10027,330,48,48], which is causing the OOM error. 
- The 48 number is a function of the number of lags and the number of latent dimensions, I think `(nlags+1) * latent_dim`. Does that check out for you? Like is the latent dimension 12? 

There are two ways I can think of to conserve memory here:
- Construct the relevant dynamics and noise matrices on the fly by passing in the set of options and the state sequence
- Avoid concerting the nth-order AR process into a 1st-order AR process when performing Kalman sampling

Option 1 above is simpler and might be straightforward used the EKF API in dynamax... 

We can definitely explore those options! In the meantime, you might have to make do with modeling a subset of the data and then applying the model to the rest of the data. Also, if you do so, make sure to avoid using "syllables_reindexed"! (see https://github.com/dattalab/keypoint-moseq/issues/72)

**Comment by r-shruthi11** [comment]
Yes your understanding of the recap is accurate. Our `latent_dim` is 16 and our `nlags` is 3 so the `ar_dim` of our dynamics matrices are `latent_dim x nlags = 48` 
Yes I was previously fitting on a subset of my dataset (~ 1/12th) and using our learned model parameters to infer the states on all our other sessions, but this doesn't seem to do a good job accurately capturing the dynamics in the held out data. 
Thanks re: syllables reindexed. I don't believe we're using that in `apply_model`; when applying, we only pass in `params` that we read from the checkpoint and states is set to `False` - so we should be okay?

**Comment by calebweinreb** [comment]
Hmm latent_dim=16 strikes me as super high. I might stop at 10 even if that doesn't explain 90% of the variance.

Regarding the syllables_reindex issue, can you explain more how you are applying the model? Is it not using the `apply_model` method? If you are using `apply_model`, then it will save the results to a `results.h5` file, and those results will include `syllables` and `syllables_reindexed`. The issue linked above refers to a bug in how `syllables_reindexed` is computed in this context. So you should be sure to use the non-reindexed syllables, and pass `use_reindexed=False` when generating trajectory plots etc.

**Comment by r-shruthi11** [comment]
Interesting - thanks for explaining that.

**Comment by calebweinreb** [comment]
We just added a new tool for fitting large datasets. See https://github.com/dattalab/keypoint-moseq/pull/79
