### ISSUE TITLE
Enable parallel scan analogues of hmm and lgssm samplers

### ISSUE THREAD

**Issue by ezhang94** [dattalab/jax-moseq#7]
## Approach
- **Parallel hmm sampler.** Adapt the [regular posterior sampler](https://github.com/probml/dynamax/blob/71ea2d44860a377409c39706f37a7c551d5f3212/dynamax/hidden_markov_model/inference.py#L487), except replace the `hmm_filter` call with that of the [parallel filter](https://github.com/probml/dynamax/blob/71ea2d44860a377409c39706f37a7c551d5f3212/dynamax/hidden_markov_model/parallel_inference.py#L21)
- **Parallel kalman sampler.** Similarly, adapt the [regular lgssm posterior sampler](https://github.com/probml/dynamax/blob/71ea2d44860a377409c39706f37a7c551d5f3212/dynamax/linear_gaussian_ssm/inference.py#L402) to call the [parallel lgssm filter](https://github.com/probml/dynamax/blob/71ea2d44860a377409c39706f37a7c551d5f3212/dynamax/linear_gaussian_ssm/parallel_inference.py#L69)

## Evaluation
- [ ] Compare run speed of sequential and parallel hmm posterior sampler
- [ ] Compare run speed of sequential and parallel lgssm posterior sampler

**Comment by calebweinreb** [comment]
Assigning this to @kaijfox...

- Currently there's a working(?) parallel lgssm implementation in this branch: https://github.com/dattalab/jax-moseq/tree/lgssm_dynamax_parallel_inference
- And there's a working(?) non-parallel (but dynamax-dependent) implementation in this branch: https://github.com/dattalab/jax-moseq/tree/lgssm_dynamax
- Note that `sigmasq` is no longer resampled in the parallel branch (see https://github.com/dattalab/jax-moseq/blob/9860860ecae1c0464b532634cb1a6449f51c4138/jax_moseq/models/keypoint_slds/gibbs.py#LL361C31-L361C52). I think this should be the default from now on (i.e. included in the merge)

Remaining tasks:
- Make sure both implementations work (without NaNs etc.) and produce sensible outputs in keypoint-moseq using the tutorial dataset (see https://keypoint-moseq.readthedocs.io/en/latest/tutorial.html)
- Add a config option in keypoint moseq for serial vs parallel. Maybe we could have the default be True but then override it (with a warning?) if there's no GPU present? The override could live in keypoint-moseq, and would be needed here https://github.com/dattalab/keypoint-moseq/blob/8958e6ba21cfcaf60a4cb2d92086b051f3532e61/keypoint_moseq/fitting.py#L51 and here https://github.com/dattalab/keypoint-moseq/blob/8958e6ba21cfcaf60a4cb2d92086b051f3532e61/keypoint_moseq/fitting.py#L308.
- Note that these changes depend some recent PRs in dynamax (https://github.com/probml/dynamax/pull/324, https://github.com/probml/dynamax/pull/321, https://github.com/probml/dynamax/pull/319). They have been merged into main but I don't think there's been a new release of dynamax recently, so they may not be included in a generic pip install of dynamax. So we either need to get the dynamax devs to do another release, or to make jax-moseq depend on the git repo rather than the pypi version of dynamax
- Once we've merged in these changes, we should make a new release and then bump pinned jax-moseq dependency in keypoint-moseq

**Comment by slinderman** [comment]
> So we either need to get the dynamax devs to do another release, or to make jax-moseq depend on the git repo rather than the pypi version of dynamax

I can do that — please remind me on Slack if I forget!

**Comment by kaijfox** [comment]
Added the flag and a conditional to call the correct (sequential/parallel) sampler and saw about a 2x speedup (avg 11.1 sec/it sequential -> avg 6.4 sec/it parallel) on a gpu node after the first iteration. As expected the first iteration does take longer for the parallelized Kalman filter due to the more complicated jitting (first iteration 11.3 sec sequential, 104 sec parallel). 

I don't see any noticeable difference in the duration distributions on produced by the tutorial notebook using these two algorithms:

__Parallel algorithm__
<img width="226" alt="parallel_duration_dist" src="https://github.com/dattalab/jax-moseq/assets/5048348/c05e321a-a70c-467d-8110-390c89d46c5d">

__Sequential algorithm__
<img width="226" alt="serial_duration_dist" src="https://github.com/dattalab/jax-moseq/assets/5048348/21ac20bb-b02e-4f2e-a8ce-69e332b7e1be">

Other small things:
- Defaults for sampling `sigmasq` updated.
- Auto-override of the `parallel_kalman` flag when no GPU present still todo.

**Comment by calebweinreb** [comment]
> > So we either need to get the dynamax devs to do another release, or to make jax-moseq depend on the git repo rather than the pypi version of dynamax
> 
> I can do that — please remind me on Slack if I forget!

Hi @slinderman! Just wanted to check in re the dynamax release. Were you planning to update the version on pypi? No worries if not - we can just have the setup requirements point to the dynamax github repo

**Comment by slinderman** [comment]
Sorry for the delay. Just published a new dynamax release: https://github.com/probml/dynamax/releases/tag/0.1.1

**Comment by calebweinreb** [comment]
Released in https://github.com/dattalab/jax-moseq/releases/tag/0.0.4. Still need to update keypoint_moseq (https://github.com/dattalab/keypoint-moseq/issues/65)
